
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import PageTransition from "../components/PageTransition";
import StairTransition from '../components/StairTransition'

import Footer from '../components/Footer'
import { Providers } from "./provider";
import AppProvider from "../AppContext.js"

const jetBrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-jetbrainsMono"
});


export const metadata = {
  title: "Amro Elmutasim",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"></link>

      <body
        className={`${jetBrainsMono.variable} flex flex-col justify-center xl:max-w-[85%] mx-auto mb-12 max-xl:mt-4`}
      >
        <AppProvider session>
          <Providers>
            
          <Header />
        
        <PageTransition>{children}</PageTransition>

        <Footer />

          </Providers>
        </AppProvider>

        
        
      </body>
    </html>
  );
}
